#if !defined(_ZZ_q_errdefs_DEFINED)
#define _ZZ_q_errdefs_DEFINED
/*===========================================================================*/

#define E_OKAY               0
#define E_INTERNAL           1
#define E_ABORTING           2
#define E_NUMBIG             3
#define E_BADCHAR            4
#define E_UNDEFIDENT         5
#define E_MULTIEQ            6
#define E_MULTIREL           7
#define E_MULTIBOOLEQ        8
#define E_QQ_FUTURE          9
#define E_KVSN              10
#define E_ALREADYDCL        11
#define E_NOKEYWORD         12
#define E_NOKEYWORDSEMI     13
#define E_NOTSETUPSECTION   14
#define E_NOTSTARTSECTION   15
#define E_NOTSTMT           16
#define E_NOTSEMI           17
#define E_SSVALOUTOFRANGE   18
#define E_NOTINTEGER        19
#define E_LINEBIG           20
#define E_BADOPTION         21
#define E_OPTIONTOOBIG      22
#define E_OPTIONTOOTINY     23
#define E_PROMOTE           24
#define E_NOTSCALAR         25
#define E_BACKWDSRNGE       26
#define E_TOOMANYERRS       27
#define E_TOOMANYERRSTHIS   28
#define E_TOOMANYWRNS       29
#define E_TOOMANYWRNSTHIS   30
#define E_FILENOTFOUND      31
#define E_NORIGHTS          32
#define E_TOOMANYFILES      33
#define E_QUOTA             34
#define E_READONLY          35
#define E_CANNOTOPEN        36
#define E_IDTRUNC           37
#define E_NUMTRUNC          38
#define E_STRINGBIG         39
#define E_VMS_ERROR         40
#define E_NOTREAL           41
#define E_NUMSTARTDOT       42
#define E_KEYWCONTEXT       43
#define E_OLDSYNTAX         44
#define E_NOCALLINGALLOWED  45
#define E_QQ_FUTURE_X       46
#define E_NOMEMORYP         47
#define E_NOMEMORYR         48
#define E_FILENAMEBIG       49
#define E_UNTERMBODY        50
#define E_UNTERMCOMMENT     51
#define E_UNTERMQUOTE       52
#define E_NOTRULESECTION    53
#define E_NOTBVAL           54
#define E_NOTIVAL           55
#define E_NOTRVAL           56
#define E_SKIPPING          57
#define E_NOTFLAGSET        58
#define E_NOTIDENT          59
#define E_NOTINPUTPROMPT    60
#define E_EMPTYLIST         61
#define E_NOTNAMEDCONSTANT  62
#define E_MISSINGTOKEN      63
#define E_NOTOPENPAREN      64
#define E_NOTCLOSEPAREN     65
#define E_SEMITOCOMMA       66
#define E_NOARRAYRANGE      67
#define E_NEGVALUE          68
#define E_NOUPPERBOUND      69
#define E_EXPROVF           70
#define E_PARMCOUNTOVF      71
#define E_TABLEOVF          72
#define E_FUNCNESTOVF       73
#define E_EXPRSTKOVF        74
#define E_EXPRLISTOVF       75
#define E_EXPROPNDOVF       76
#define E_FUNCBODYOVF       77
#define E_SPACEPIXOVF       78
#define E_RULEOVF           79
#define E_NOTOPENBRACKET    80
#define E_NOTCLOSEBRACKET   81
#define E_NOTIDLIT          82
#define E_NOTWHOLEARRAY     83
#define E_NOTARRAY          84
#define E_NOTBOOLREL        85
#define E_TYPEMISMATCH      86
#define E_NOTBOOLITEM       87
#define E_NOTNUMBITEM       88
#define E_NOTEQUALSIGN      89
#define E_BADREGTOKEN       90
#define E_BADIMPTOKEN       91
#define E_NOTRATEEXPR       92
#define E_CMDLINEVALBIG     93
#define E_TOOFEWCALLING     94
#define E_TOOMANYCALLING    95
#define E_NOTSSVINIMPL      96
#define E_SSVNOTLISTED      97
#define E_NOTSSVORCONST     98
#define E_WRONGSECTION      99
#define E_RNGEOVF          100
#define E_NOTCOLON         101
#define E_NEGROOT          102
#define E_LNOFNEG          103
#define E_EXPOVF           104
#define E_TANSING          105
#define E_BADARCSIN        106
#define E_BADARCCOS        107
#define E_NOREALS          108
#define E_NEGTOREAL        109
#define E_REALOVF          110
#define E_INTEGEROVF       111
#define E_IMOD0            112
#define E_IDVD0            113
#define E_RDVD0            114
#define E_AMBIGUOUS        115
#define E_NOSPACE          116
#define E_NOSTART          117
#define E_CANNOTMIX        118
#define E_MISSINGEXPR      119
#define E_INTBEFOREOF      120
#define E_OFTOOBIG         121
#define E_NOTCOMMA         122
#define E_BADVALUE         123
#define E_NOTSSV           124
#define E_NOTBY            125
#define E_NOTWITHFAST      126
#define E_NOTOPENANGLE     127
#define E_NOTCLOSEANGLE    128
#define E_RELINNUMERIC     129
#define E_INDEPENDENT      130
#define E_NOTTHENORTRANTO  131
#define E_REBUILDHUGE      132
#define E_IXONSCALAR       133
#define E_EVALSTOVAR       134
#define E_NOTIN            135
#define E_NUMERICMISMATCH  136
#define E_INDEXEDBYPARENS  137
#define E_ASSERT           138
#define E_DIMSCALAR        139
#define E_DIMOUTOFBOUNDS   140
#define E_EVALSSVPRS       141
#define E_EMPTYPIXLIST     142
#define E_RATECOUNTANGLE   143
#define E_RATECOUNT        144
#define E_FUTUREOPTION     145
#define E_NODEATHS         146
#define E_NOTRANTOS        147
#define E_SCOPE            148
#define E_SCOPEACTIVE      149
#define E_ARITHINBOOL      150
#define E_BOOLINARITH      151
#define E_RECURSIVE        152
#define E_NOTRANTOSOUT     153
#define E_NOTUNIX          154
#define E_REALEQ           155
#define E_PROMPTTRUNC      156
#define E_COMMENTTURNEDOFF 157
#define E_SUREIDNOTUNIQUE  158
#define E_TRANTONOTUSED    159
#define E_DIMPRODHUGE      160
#define E_DIMINCONSISTANT  161
#define E_DOUBLEWILD       162
#define E_WILDCONTEXT      163
#define E_TOOMANYSUBS      164
#define E_TOOFEWSUBS       165
#define E_NOTDOUBLE        166
#define E_BOOLTOKENMISSING 167
#define E_TWICEINTTO       168
#define E_CLOPT            169
#define E_ICYC0            170
#define E_RECOVERTODEATH   171
#define E_RECOVERTOPRUNE   172
#define E_VARDUMMY         173
#define E_OPTIONALIGN      174
#define ERROR_COUNT        175 /* must be last */

#define SURE_CONSTANT_TRUNC_NCHARS 12

/*===========================================================================*/
#endif
