#!/bin/sh
echo "=============================================================================="
echo "=============================================================================="
echo "=============================================================================="
echo "=============================================================================="
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo "=============================================================================="
echo "=============================================================================="
echo "=============================================================================="
echo "=============================================================================="

arch=`uname -s | awk '{print tolower(substr($0,0,6))}' -`
case $arch in
     darwin) myarch=macos;;
     linux)  myarch=linux;;
     cygwin) myarch=cygwin;;
     *)      echo "Only run under Darwin, Linux, and Cygwin";exit 1
esac

if [[ "$myarch" == 'cygwin' ]]; then
javac -g -d bin  -Xlint:all,-serial src/gov/nasa/larcfm/Reliab/*.java
else
javac -g -d bin -Xlint:all,-serial src/gov/nasa/larcfm/Reliab/*.java
fi
